# Generated by Django 5.0.2 on 2025-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key_points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='suggested_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='clarity_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='technical_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design')], max_length=20),
        ),
    ]
